services:
  app:
    build: .
    ports:
      - "5173:5173"
      - "3001:3001"
    volumes:
      - .:/app:z
      - ./node_modules:/app/node_modules
      - ./.pnpm-store:/app/.pnpm-store
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY:-}
    tty: true
    stdin_open: true
